apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-controller-manager
spec:
  template:
    spec:
      serviceAccountName: search-controller-manager
      automountServiceAccountToken: true
      containers:
      - name: manager
        env:
        - name: MULTI_TENANT
          value: "true"
        - name: PROJECT_LABEL_SELECTOR
          value: ""
