apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/apiserver
  - ../../base/resource-indexer
  - ../controller-manager/core-control-plane

images:
  - name: ghcr.io/datum-cloud/search
    newTag: latest
