apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-indexer
spec:
  template:
    spec:
      serviceAccountName: resource-indexer
      automountServiceAccountToken: true
      containers:
      - name: indexer
        env:
        - name: ENABLE_MULTI_TENANCY
          value: "true"
