---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: search-controller-manager
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resourcemanager.miloapis.com
  resources:
  - projects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - search.miloapis.com
  resources:
  - resourceindexpolicies
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - search.miloapis.com
  resources:
  - resourceindexpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - search.miloapis.com
  resources:
  - resourceindexpolicies/status
  verbs:
  - get
  - patch
  - update
