apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: search.miloapis.com-searcher
  namespace: milo-system
  labels:
    app.kubernetes.io/name: searcher
    app.kubernetes.io/part-of: search.miloapis.com
spec:
  launchStage: Beta
  includedPermissions:
    - search.miloapis.com/resourcesearchqueries.create
