apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: search.miloapis.com-resourcesearchqueries
spec:
  serviceRef:
    name: "search.miloapis.com"
  kind: ResourceSearchQuery
  plural: resourcesearchqueries
  singular: resourcesearchquery
  permissions:
    - create
    - get
