apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: search.miloapis.com-searchqueries
spec:
  serviceRef:
    name: "search.miloapis.com"
  kind: SearchQuery
  plural: searchqueries
  singular: searchquery
  permissions:
    - create
