apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  # ServiceMonitors for metrics collection
  - servicemonitors/search-apiserver-servicemonitor.yaml
  - servicemonitors/resource-indexer-servicemonitor.yaml
