apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../nats

patches:
  - target:
      kind: HelmRelease
      name: nats
      namespace: nats-system
    patch: |-
      - op: replace
        path: /spec/values/promExporter/podMonitor/enabled
        value: false
